backend:
  name: git-gateway
  branch: playground/next

media_folder: "/static/images"
# FIXME: Testing documentation
publis_mode: editorial_workflow
show_preview_links: true
site_url: "https://netlify-with-gatsby4blog.netlify.app"
display_url: "https://netlify-with-gatsby4blog.netlify.app"
# --->

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/data/blog"
    create: true
    slug: "{{slug}}"
    # Wehere it create images
    media_folder: "/static/images/blog"
    # media_folder: ""
    # where use the images
    public_folder: "/images/blog"
    # public_folder: ""
    path: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Author", name: "author", widget: "select", options: ["4GeeksAcademy", "MRiciglianoC", "alesanchezr"]}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "string"}
      - { label: "Link", name: "link", widget: "string", required: false}
      # TODO: Ocultar slug
      - { label: "Slug", name: "slug", widget: "string", default: "{{slug}}"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image"}
      # - { label: "Avatar", name: "avatar", widget: "image"}
      - { label: "Categories", name: "categories", widget: "list"}
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Lang", name: "lang", widget: "select", options: ["us", "es"], default: ["us"] }
      - { label: "Status", name: "status", widget: "select", options: ["published", "draft", "unassigned"]}
      - { label: "Featured", name: "featured", widget: "boolean", default: false}
      - { label: "Body", name: "body", widget: "markdown" }
