name: Cypress Test
on:
  push:
    branches:
      - development
  pull_request:
    branches: 
      - development
jobs:
  cypress-test:
    name: Test with Server
    runs-on: ubuntu-latest
    env: # environment variable
      WEBSITE_BC_API_TOKEN: ${{ secrets.WEBSITE_BC_API_TOKEN}}
      TEST: secret12345
    # strategy:
    #   matrix:
    #     node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm i
        
      - name: Running Tests
        run: npm run run:e2e
        # Install NPM dependencies, cache them correctly
        # uses: cypress-io/github-action@v2.9.7
        # with:
        #   start: npm run run:e2e
        #   browser: electron
        #   wait-on-timeout: 1000
        #   config: pageLoadTimeout=100000,baseUrl=http://localhost:8080
        # env: # environment variable
        #   WEBSITE_BC_API_TOKEN: ${{ secrets.WEBSITE_BC_API_TOKEN}}
