name: Cypress Test
on:
  push:
    branches:
      - development
  pull_request:
    branches: 
      - development
jobs:
  cypress-test:
    name: Test with Server
    runs-on: ubuntu-latest
    env: # environment variable
      WEBSITE_BC_API_TOKEN: ${{ secrets.WEBSITE_BC_API_TOKEN}}
    # strategy:
    #   matrix:
    #     node-version: [14.x]
    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v2
      - name: Running Tests
        # Install NPM dependencies, cache them correctly
        uses: cypress-io/github-action@v2.9.7
        with:
          # build: npm run build
          start: npm start
          browser: electron
          wait-on-timeout: 1000
          config: pageLoadTimeout=100000,baseUrl=http://localhost:8000
        # env: # environment variable
        #   WEBSITE_BC_API_TOKEN: ${{ secrets.WEBSITE_BC_API_TOKEN}}
