name: Cypress Test
on:
  push:
    branches:
      - development
  pull_request:
    branches: 
      - development
jobs:
  cypress-test:
    name: Test with Server
    runs-on: ubuntu-latest
    env: # environment variable
      GATSBY_BREATHECODE_HOST: https://breathecode-cypress.herokuapp.com/v1
    # strategy:
    #   matrix:
    #     node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Running Tests
        # Install NPM dependencies, cache them correctly
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run serve
          browser: electron
          wait-on: 'http://localhost:8080'
          config: pageLoadTimeout=100000,baseUrl=http://localhost:8080
