name: Cypress Test
on:
  push:
    branches:
      - development
  pull_request:
    branches: 
      - development

jobs:
  cypress-test:
    name: Test with Server
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Running Tests
        # Install NPM dependencies, cache them correctly
        uses: cypress-io/github-action@v2.9.7
        with:
          # env: # Or as an environment variable
          #   WEBSITE_BC_API_TOKEN: ${{ secrets.WEBSITE_BC_API_TOKEN }}
          build: npm run build
          # build: npm start
          start: npm run serve
          # start: npm run test:e2e
          browser: electron
          # wait-on: http://localhost:8000
          wait-on-timeout: 1000
          config: pageLoadTimeout=100000,baseUrl=http://localhost:8080
          # spec: cypress/integration/tests/*
