name: Cypress CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          browser: chrome
          spec: cypress/integration/tests/*
          # wait-on: 'http://localhost:8000'
          # wait-on-timeout: 120
          # env: stage=LOCAL
