name: Cypress Test
on:
  push:
    branches:
      - development
  pull_request:
    branches: 
      - development

jobs:
  cypress-test:
    name: Test with Server
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "echo "WEBSITE_BC_API_TOKEN=${{ secrets.WEBSITE_BC_API_TOKEN }}" >> $GITHUB_ENV
      # - name: Setup npm package
      #   run: npm install
      # - name: Run Server
      #   run: npm run start:gatsby
      - name: Running Tests
        # Install NPM dependencies, cache them correctly
        # and run all Cypress tests
        uses: cypress-io/github-action@v2.9.7
        # env: # Or as an environment variable
        #   WEBSITE_BC_API_TOKEN: ${{ secrets.WEBSITE_BC_API_TOKEN }}
        with:
          build: npm run build
          start: npm run serve
          browser: electron
          wait-on-timeout: 1000
          config: pageLoadTimeout=100000,baseUrl=http://localhost:8080
