name: Cypress Test
on:
  push:
    branches:
      - development
  pull_request:
    branches: 
      - development

jobs:
  cypress-test:
    name: Runs on Ubuntu
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Running Cypress Tests
        uses: cypress-io/github-action@v2.9.7
        with:
          start: npm start
          browser: chrome
          wait-on: http://localhost:8000
          config: pageLoadTimeout=100000,baseUrl=http://localhost:8000
          # spec: cypress/integration/tests/*
